#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
./.config/polybar/shades/launch.sh &
#feh --bg-fill /home/oselium/Documents/Images/spacesurf.png
feh --bg-fill /home/oselium/Documents/Images/1c1c1c.png

bspc monitor -d I II III IV V VI

bspc config normal_border_color \#1c1c1c
bspc config focused_border_color \#d3d3d3

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled

