#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias code='code & disown; exit'
alias ls='ls -a --color=auto'
alias purge='sudo pacman -Rsn $(pacman -Qdtq)'
alias update='sudo pacman -Syu'
alias weather='function _weather(){ curl wttr.in/$1;};_weather'

PS1='[\[\033[00;32m\]\u\[\033[00m\]@\h \[\033[1;31m\]\W\[\033[00m\]]\$ '
export LS_COLORS="$LS_COLORS:ow=1;34:tw=1;34:di=1;34:fi=1;97:"
